### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by DBachiniLima** [ianklatzco/twitter-to-bsky#16]
I have to say that I am not very familiar with using applications like this (I always think that there is some step that is obvious to everyone and that I just don't know what it is), but I believe that this error is beyond my limitation in knowing how to make it work.

Traceback (most recent call last):
  File "E:\Downloads\twitter\twitter-to-bsky-master\main.py", line 13, in <module>
    c = f.read().replace("window.YTD.tweets.part0 = ", "")
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 25882: character maps to <undefined>

For information, I speak Portuguese so I suppose the problem may have arisen from the fact that several terms have accents, which are not usually present in English.

**Comment by Umutoku** [comment]
f = open(TWEETS_JS_PATH, encoding="utf8") --12 line
