### ISSUE TITLE
wrong but verified passwrd

### ISSUE THREAD

**Issue by solertoyo** [ianklatzco/twitter-to-bsky#21]
erro
```
`Traceback (most recent call last):
  File "main.py", line 70, in <module>
    main()
  File "main.py", line 66, in main
    atpt.login(USERNAME, PASSWORD)
  File "/home/ant1/.local/lib/python3.8/site-packages/atprototools/__init__.py", line 19, in login
    raise ValueError("No access token, is your password wrong?")
ValueError: No access token, is your password wrong?
```
`

**Comment by celozaga** [comment]
same issue

**Comment by andreikobe** [comment]
same issue!

**Comment by cpbl** [comment]
Same issue. username is correct. I checked my password.   I'm setting the password in BASH using `export PASSWORD="soi$oiu#lkjlas!"`
(that's not my  real password), understanding that those special characters do not need to be escaped in this context.

**Comment by Gsuss** [comment]
Somehow related to this issue and, as this is the first result it comes in Google when you search for the issue, allow me to say that if you're using an alternative PDS (not bsky.app) for your account, you need to change the file __init__.py from the installed atprototools installed via pip.

In my case, because I created a venv to run the script, that file is located in /root/.venvs/MyEnv/lib/python3.11/site-packages/atprototools/__init__.py. 

The exact lane to change is `ATP_HOST = "https://bsky.app"` for `ATP_HOST = "https://YOUR_PDS_URL"`, line number 3.

**Comment by webash** [comment]
Use an app password. You can get one from the security settings: 
https://bsky.app/settings/app-passwords
