### ISSUE TITLE
wrong but verified passwrd

### ISSUE THREAD

**Issue by solertoyo** [ianklatzco/twitter-to-bsky#22]
error
``
Traceback (most recent call last):
  File "main.py", line 70, in <module>
    main()
  File "main.py", line 66, in main
    atpt.login(USERNAME, PASSWORD)
  File "/home/username/.local/lib/python3.8/site-packages/atprototools/__init__.py", line 19, in login
    raise ValueError("No access token, is your password wrong?")
ValueError: No access token, is your password wrong?
``

`

**Comment by solertoyo** [comment]
I simply forgot to add "social.bsky" in account name !

**Comment by solertoyo** [comment]
working fine !
