### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 4780: character maps to <undefined>

### ISSUE THREAD

**Issue by mavsanchez** [ianklatzco/twitter-to-bsky#25]
$ python main.py
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    c = f.read().replace("window.YTD.tweets.part0 = ", "")
  File "C:\Users\maver\anaconda3\envs\sandbox\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 4780: character maps to <undefined>
(sandbox)

**Comment by mavsanchez** [comment]
Added, encoding="utf8" on line 12
